# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

ssteps:
- script: |
    dotnet restore
    dotnet build --configuration $(buildConfiguration) --no-restore
    dotnet test AzureDemo.Tests/AzureDemo.Tests.csproj --configuration $(buildConfiguration) --filter Category=Unit --logger trx --no-build
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY --no-build

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: 'e4a1b775-a4c2-4daf-920f-9c4c85ffe9e4'
    WebAppName: 'azureDemo12944'
    DeployToSlotFlag: true
    ResourceGroupName: 'AzureDemo'
    SlotName: staging

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'e4a1b775-a4c2-4daf-920f-9c4c85ffe9e4'
    WebAppName: 'azureDemo12944'
    ResourceGroupName: 'AzureDemo'
    SourceSlot: staging
